
debug: true

mongo:
  link: mongodb+srv://developer:eAQiCvYa2nQLKVPZ@devcluster-g4uwh.mongodb.net/test?retryWrites=true&w=majority
  database: metaldev

cors:
  allowed:
    pattern: ^https?://(.*)metal(shop|back|dev|front)\.chasemoskal\.com(|:8\d{3})$
    flags: i
  forbidden: null

authServer:
  port: 8000
  googleClientId: 501512445110-q3i6vl4ihfas2act2euehgppiats6gor.apps.googleusercontent.com
  accessTokenLifespan: 600000
  refreshTokenLifespan: 7776000000
  nicknameStructure:
    - [adjectives, colors]
    - [animals]

liveshowServer:
  port: 8003

questionsServer:
  port: 8002
  authServerOrigin: http://auth:8000
  profileServerOrigin: http://profile:8001
