
debug: true

mongo:
  link: mongodb+srv://developer:eAQiCvYa2nQLKVPZ@devcluster-g4uwh.mongodb.net/test?retryWrites=true&w=majority
  database: metaldev

cors:
  allowed:
    pattern: ^https?://(.*)metal(shop|back|dev|front)\.chasemoskal\.com(|:8\d{3})$
    flags: i
  forbidden: null

authServer:
  port: 8000
  googleClientId: 501512445110-q3i6vl4ihfas2act2euehgppiats6gor.apps.googleusercontent.com
  accessTokenLifespan: 600000
  refreshTokenLifespan: 7776000000
  nicknameStructure:
    - [adjectives, colors]
    - [animals]

paywallServer:
  port: 8003
  authServerOrigin: http://auth:8000
  premiumStripePlanId: plan_H5oUIjw9895qDj
  stripeApiKey: pk_test_NEDtuftU6ziXyM4Y6PDrifPl00g6q5efYe
  stripeSecret: sk_test_Pj55B8JGeQyJeMxhcRc3ljEs00V9zwM3FA
  stripeWebhooksSecret: whsec_0xVpgCAoXsXUmlalCAMFRCWnRNaiGJ0x

liveshowServer:
  port: 8003

questionsServer:
  port: 8002
  authServerOrigin: http://auth:8000
