
{{- $images := .Values.images -}}
{{- $checksum := include (print $.Template.BasePath "/secret-config.yaml") . | sha256sum -}}
{{- $rname := include "metalback.fullname" . -}}

{{- range $mname, $microservice := .Values.microservices -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $rname }}-{{ $mname }}
spec:
  replicas: {{ $microservice.replicas }}
  selector:
    matchLabels:
      app: {{ $rname }}-{{ $mname }}
  template:
    metadata:
      labels:
        app: {{ $rname }}-{{ $mname }}
      annotations:
        checksum: {{ $checksum }}
    spec:
      imagePullSecrets:
      - name: dockerconfigjson-github-com
      volumes:
      - name: {{ $rname }}-{{ $mname }}-config-volume
        secret:
          secretName: {{ $rname }}-secret-config
      containers:
      - image: "{{ $microservice.image }}:{{ $images.tag }}"
        imagePullPolicy: {{ $images.pullPolicy }}
        name: {{ $mname }}
        ports:
        - containerPort: {{ $microservice.port }}
        volumeMounts:
        - name: {{ $rname }}-{{ $mname }}-config-volume
          mountPath: /app/config
          readOnly: true

---

apiVersion: v1
kind: Service
metadata:
  name: {{ $rname }}-{{ $mname }}-service
spec:
  selector:
    app: {{ $rname }}-{{ $mname }}
  ports:
  - protocol: TCP
    port: {{ $microservice.port }}
    targetPort: {{ $microservice.port }}

---
{{- end -}}
