
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
spec:
  selector:
    matchLabels:
      app: web-server
  replicas: {{ .Values.web.replicas }}
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: web-server
        image: "{{ .Values.web.image }}:{{ .Values.images.tag }}"
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        ports:
        - containerPort: 80
        env:
        - name: HTTPS_METHOD
          value: noredirect

---

apiVersion: v1
kind: Service
metadata:
  name: web-server
spec:
  selector:
    app: web-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
