
ingress:
  class: nginx
  domain: on.metalshop.dev
  tls:
    production: true
    email: chasemoskal@gmail.com

microservices:
  auth:
    image: chasemoskal/auth-server:latest
    replicas: 2
    port: 8000
  liveshow:
    image: chasemoskal/liveshow-server:latest
    replicas: 2
    port: 8001
  paywall:
    image: chasemoskal/paywall-server:latest
    replicas: 2
    port: 8002
  questions:
    image: chasemoskal/questions-server:latest
    replicas: 2
    port: 8003
  schedule:
    image: chasemoskal/schedule-server:latest
    replicas: 2
    port: 8004
  settings:
    image: chasemoskal/settings-server:latest
    replicas: 2
    port: 8005
