
ingress:
  domain: metalshop.chasemoskal.com
  tls: ~

web:
  image: metalshop-web:dev
  replicas: 1

microservices:
  auth:
    image: metalshop-auth-server:dev
    replicas: 1
  liveshow:
    image: metalshop-liveshow-server:dev
    replicas: 1
  paywall:
    image: metalshop-paywall-server:dev
    replicas: 1
  questions:
    image: metalshop-questions-server:dev
    replicas: 1
  schedule:
    image: metalshop-schedule-server:dev
    replicas: 1
  settings:
    image: metalshop-settings-server:dev
    replicas: 1
