
config: config-prod

ingress:
  class: nginx
  domain: metalshop.dev
  tls:
    production: true
    email: chasemoskal@gmail.com

images:
  tag: latest # overwrite with git hash
  pullPolicy: IfNotPresent

web:
  image: chasemoskal/metalshop-web
  replicas: 2

microservices:
  auth:
    image: chasemoskal/metalshop-auth-server
    replicas: 2
    port: 8000
  liveshow:
    image: chasemoskal/metalshop-liveshow-server
    replicas: 2
    port: 8001
  paywall:
    image: chasemoskal/metalshop-paywall-server
    replicas: 2
    port: 8002
  questions:
    image: chasemoskal/metalshop-questions-server
    replicas: 2
    port: 8003
  schedule:
    image: chasemoskal/metalshop-schedule-server
    replicas: 2
    port: 8004
  settings:
    image: chasemoskal/metalshop-settings-server
    replicas: 2
    port: 8005
