
ingress:
  class: nginx
  domain: metalshop.dev
  tls:
    production: true
    email: chasemoskal@gmail.com

images:
  pullPolicy: Always

web:
  image: docker.pkg.github.com/chase-moskal/metalshop/web:production
  replicas: 2

microservices:
  auth:
    image: docker.pkg.github.com/chase-moskal/metalshop/auth-server:production
    replicas: 2
    port: 8000
  liveshow:
    image: docker.pkg.github.com/chase-moskal/metalshop/liveshow-server:production
    replicas: 2
    port: 8001
  paywall:
    image: docker.pkg.github.com/chase-moskal/metalshop/paywall-server:production
    replicas: 2
    port: 8002
  questions:
    image: docker.pkg.github.com/chase-moskal/metalshop/questions-server:production
    replicas: 2
    port: 8003
  schedule:
    image: docker.pkg.github.com/chase-moskal/metalshop/schedule-server:production
    replicas: 2
    port: 8004
  settings:
    image: docker.pkg.github.com/chase-moskal/metalshop/settings-server:production
    replicas: 2
    port: 8005
