
debug: true

mongo:
  link: mongodb+srv://developer:eAQiCvYa2nQLKVPZ@devcluster-g4uwh.mongodb.net/test?retryWrites=true&w=majority
  database: metaldev

cors:
  allowed:
    pattern: ^https://(|.+\.)stage\.metalshop\.dev$
    flags: i
  forbidden: null

authServerOrigin: http://auth

authServer:
  port: 8000
  googleClientId: 25671840068-bbc18an921lc5tqrer7vp0h1obr1tvok.apps.googleusercontent.com
  accessTokenLifespan: 600000
  refreshTokenLifespan: 7776000000
  nicknameStructure:
    - [adjectives, colors]
    - [animals]

liveshowServer:
  port: 8001

paywallServer:
  port: 8002
  premiumStripePlanId: plan_H5oUIjw9895qDj
  stripeApiKey: pk_test_NEDtuftU6ziXyM4Y6PDrifPl00g6q5efYe
  stripeSecret: sk_test_Pj55B8JGeQyJeMxhcRc3ljEs00V9zwM3FA
  stripeWebhooksSecret: whsec_0xVpgCAoXsXUmlalCAMFRCWnRNaiGJ0x

questionsServer:
  port: 8003

scheduleServer:
  port: 8004

settingsServer:
  port: 8005
